#persistent-volume-claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: crud-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  


