#persistent-volume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: crud-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres"

  


